// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxFrwTEX7eTXI5pSRKA_efazlxNGM68vI',
    appId: '1:169314754544:web:c8755d1153cc813ac24735',
    messagingSenderId: '169314754544',
    projectId: 'authentication-c1d5b',
    authDomain: 'authentication-c1d5b.firebaseapp.com',
    storageBucket: 'authentication-c1d5b.appspot.com',
    measurementId: 'G-8PEZ3J717X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQYzRDhwSJOg4h_jl9l_some593F5OmjM',
    appId: '1:169314754544:android:cc86278130cfca05c24735',
    messagingSenderId: '169314754544',
    projectId: 'authentication-c1d5b',
    storageBucket: 'authentication-c1d5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlcOoDrSHvi1hDZ9Q6RKbr0nsuxeqa8kM',
    appId: '1:169314754544:ios:76d15d69106669edc24735',
    messagingSenderId: '169314754544',
    projectId: 'authentication-c1d5b',
    storageBucket: 'authentication-c1d5b.appspot.com',
    iosClientId: '169314754544-5aockkg7gu6538gmg1gs32b79shqsdvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlcOoDrSHvi1hDZ9Q6RKbr0nsuxeqa8kM',
    appId: '1:169314754544:ios:76d15d69106669edc24735',
    messagingSenderId: '169314754544',
    projectId: 'authentication-c1d5b',
    storageBucket: 'authentication-c1d5b.appspot.com',
    iosClientId: '169314754544-5aockkg7gu6538gmg1gs32b79shqsdvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxFrwTEX7eTXI5pSRKA_efazlxNGM68vI',
    appId: '1:169314754544:web:00652a54260018bdc24735',
    messagingSenderId: '169314754544',
    projectId: 'authentication-c1d5b',
    authDomain: 'authentication-c1d5b.firebaseapp.com',
    storageBucket: 'authentication-c1d5b.appspot.com',
    measurementId: 'G-6PCESJQBSK',
  );
}
